Minor Changes
ZennoLab/capmonstercloud-client-dotnet pull request #23
Opened 2023-07-28 14:53 UTC by TheVisual

* Bump TargetFramework to netstandard2.1
* Update Copyright date 2022 -> 2023
* Bump Newtonsoft.Json because version used is vulnerable
* Bump  tests TargetFramework net5.0 (EOL) -> net6.0

2023-09-27 14:56 UTC, azeriker requested changes

2023-09-27 14:56 UTC, azeriker commented on CapMonsterCloud.Client.Tests/CapMonsterCloud.Client.Tests.csproj
> +    <TargetFramework>net6.0</TargetFramework>
need to up .net version in workflows as well

2023-09-27 14:56 UTC, azeriker commented on CapMonsterCloud.Client/CapMonsterCloud.Client.csproj
> +    <TargetFramework>netstandard2.1</TargetFramework>
we are not using any of 2.1 apis, no need in this change

2023-10-01 06:06 UTC, TheVisual commented
@azeriker Updated 👍 Sorry for late update also bumped more decencies

2023-10-06 18:46 UTC, azeriker approved these changes

2023-10-06 18:49 UTC, merged